# environment_versions.yml file that contains exact version numbers of what is currently installed. We take the pip installs from the original environment file, though, as conda env export does apparently not keep track of the specific source of pip wheel installs. That being said, this is only to keep track of what is installed locally. Due to differences in software availability across operating systems, we will have to resort to building Docker images from the manually built environment.yml file to ensure reproducibility.
name: nitrateflux
channels:
  - conda-forge
dependencies:
  - affine=2.3.0
  - appdirs=1.4.3
  - appnope=0.1.0
  - arrow-cpp=0.14.1
  - asciitree=0.3.3
  - asn1crypto=1.0.0
  - attrs=19.2.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bokeh=1.3.4
  - boost-cpp=1.70.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2019.9.11
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.9.11
  - cffi=1.12.3
  - cfitsio=3.470
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.2
  - cmocean=2.0
  - colorcet=2.0.1
  - colorspacious=1.1.2
  - contextily=1.0rc2
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask=2.5.0
  - dask-core=2.5.0
  - datashader=0.7.0
  - datashape=0.5.4
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - descartes=1.1.0
  - distributed=2.5.1
  - docker-py=4.1.0
  - docker-pycreds=0.4.0
  - double-conversion=3.1.5
  - entrypoints=0.3
  - escapism=1.0.0
  - esmf=7.1.0
  - esmpy=7.1.0
  - expat=2.2.5
  - fasteners=0.14.1
  - fiona=1.8.7
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - fsspec=0.5.1
  - gdal=2.4.2
  - geckodriver=0.24.0
  - geographiclib=1.50
  - geopandas=0.6.0
  - geoplot=0.3.2
  - geopy=1.20.0
  - geos=3.7.2
  - geotiff=1.5.1
  - geoviews=1.6.3
  - geoviews-core=1.6.3
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.1.7
  - glib=2.58.3
  - glog=0.4.0
  - grpc-cpp=1.23.0
  - gsw=3.3.1
  - h5netcdf=0.7.4
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - heapdict=1.0.1
  - holoviews=1.12.5
  - hvplot=0.4.0
  - icu=64.2
  - idna=2.8
  - imageio=2.5.0
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.14.0
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter-repo2docker=0.10.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libcxx=9.0.0
  - libcxxabi=9.0.0
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libevent=2.1.10
  - libffi=3.2.1
  - libgdal=2.4.2
  - libgfortran=4.0.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.5
  - libprotobuf=3.8.0
  - libsodium=1.0.17
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libuv=1.32.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvm-openmp=9.0.0
  - llvmlite=0.29.0
  - locket=0.2.0
  - lxml=4.4.1
  - lz4-c=1.8.3
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mercantile=1.1.2
  - mistune=0.8.4
  - monotonic=1.5
  - mpi=1.0
  - mpich=3.3.1
  - msgpack-python=0.6.2
  - multipledispatch=0.6.0
  - munch=2.3.2
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf-fortran=4.4.5
  - netcdf4=1.5.1.2
  - networkx=2.3
  - nodejs=12.11.1
  - notebook=6.0.1
  - numba=0.45.1
  - numcodecs=0.6.3
  - numpy=1.17.2
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1c
  - owslib=0.18.0
  - packaging=19.2
  - pandas=0.25.1
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - panel=0.6.3
  - param=1.9.1
  - parquet-cpp=1.5.1
  - parso=0.5.1
  - partd=1.0.0
  - patsy=0.5.1
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.0
  - pip=19.2.3
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - proj4=6.1.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - pyarrow=0.14.1
  - pycparser=2.19
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pyepsg=0.4.0
  - pygments=2.4.2
  - pykdtree=1.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyproj=2.2.1
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-json-logger=0.1.11
  - pytz=2019.2
  - pyviz_comms=0.7.2
  - pywavelets=1.0.3
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - rasterio=1.0.28
  - re2=2019.09.01
  - readline=8.0
  - requests=2.22.0
  - rtree=0.8.3
  - ruamel.yaml=0.16.5
  - ruamel.yaml.clib=0.2.0
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - selenium=3.141.0
  - semver=2.8.1
  - send2trash=1.5.0
  - setuptools=41.2.0
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - thrift-cpp=0.12.0
  - tk=8.6.9
  - toml=0.10.0
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - tzcode=2019a
  - uriparser=0.9.3
  - urllib3=1.25.6
  - viscm=0.7
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - websocket-client=0.56.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xarray=0.13.0
  - xerces-c=3.2.2
  - xesmf=0.2.0
  - xlrd=1.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zarr=2.3.2
  - zeromq=4.3.2
  - zict=1.0.0
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - git+https://github.com/varnion/svg_stack@d324a93a42d80c98a2ed27e4004a1781b44ffc0a
